fix mybatis build error
eairp/mybatis pull request #113
Opened 2022-09-23 13:34 UTC by Jzow

#112 use bson error use type question

2022-09-23 13:36 UTC, Jzow reviewed
fix

2022-09-23 13:36 UTC, Jzow commented on mybatis/Cargo.toml
> +rbson = { version = "2.0.4"}
This may affect macro adjustment

2022-09-25 06:30 UTC, xuhanfeng2219 approved these changes

2022-09-25 06:33 UTC, xuhanfeng2219 approved these changes

2022-09-25 06:36 UTC, xuhanfeng2219 requested changes
agree change to jow's mind to fixed this bug

2022-09-25 15:20 UTC, Jzow reviewed
you have reviewed it again. Maybe you need to appro it

2022-09-27 02:31 UTC, xuhanfeng2219 approved these changes
agree change version

2022-09-27 03:43 UTC, merged